### ISSUE TITLE
Unable to connect to Azure Synapse Analytics Dedicated SQL Pool using dbops.

### ISSUE THREAD

**Issue by DesaCh01** [dataplat/dbops#133]
While trying to connect to Azure Synapse Analytics dedicated SQL Pool via dbops, I encountered the following errors;

_**Login failed for user '*****'**_

But, with the same credentials, I was able to login into the SQL pool via SSMS.

**Comment by nvarscar** [comment]
Are you using native SQL Login credentials or Azure Active Directory credentials? Please show the command you're using (with an extra -Debug switch) and full output. I don't have access to Azure Synapse Analytics to test your configuration, but, to simplify things, you should be able to run Invoke-DBOQuery instead of whatever you're running.

**Comment by DesaCh01** [comment]
Hi @nvarscar , 

Apologies for the late reply.
I'm using native SQL login credentials stored as Github secrets.  The command that I'm using is as follows:

### $SecurePw=ConvertTo-SecureString ${{ secrets.SYNAPSE_PASSWORD }} –asplaintext –force

### Install-DBOScript -ScriptPath scripts -sqlinstance ${{ secrets.SYNAPSE_INSTANCE_DEV }} -Database ${{ secrets.SYNAPSE_DATABASE }} -UserName ${{ secrets.SYNAPSE_USERNAME }} -Password $SecurePw -SchemaVersionTable $null -Debug

Also, I'm attaching the log output for this.
[logs_309.zip](https://github.com/dataplat/dbops/files/8638637/logs_309.zip)

**Comment by nvarscar** [comment]
In your logs, the error looks like this:

```
System.Data.SqlClient.SqlException (0x80131904): Login failed for user '***'.
```

this seems to be an authentication issue rather than a driver problem. Your command was:

```
Install-DBOScript -ScriptPath scripts -sqlinstance *** -Database *** -UserName *** *** -SchemaVersionTable $null -Debug
```

Not sure if that's the problem but I don't see a `-Password` parameter.
