### ISSUE TITLE
Ansible module

### ISSUE THREAD

**Issue by lowlydba** [dataplat/dbops#136]
Hey! So I'm working on an ansible collection (https://github.com/lowlydba/lowlydba.sqlserver) for SQL Server to handle a lot of instance-level tasks, mostly by implementing dbatools. 

I just noticed on the readme that an ansible module is mentioned for future releases. If there was still interest in this, I'd love to collaborate and possibly house it in my collection.

**Comment by nvarscar** [comment]
That's some stellar work @lowlydba ! I considered an Ansible module before, but it is currently on a back burner, not sure if I will start looking into it anytime soon. We can still have a discussion on whether there are good use cases for DBOps in Ansible.

I think a good first step would be something like Install-DBOScript/Install-DBOPackage wrapper.

**Comment by lowlydba** [comment]
Cool! I have an upcoming need for this module and will probably implement it soon via https://github.com/lowlydba/lowlydba.sqlserver/issues/103. It will probably be a super simple Install-DboScript wrapper. I can CC you on the PR for it if you're interested in taking a look.

**Comment by lowlydba** [comment]
Forgot to @, but this PR is closed and is now implemented as the `install_script` module in the aforementioned repo.

**Comment by nvarscar** [comment]
That looks great! Thanks for paging.
