### ISSUE TITLE
Skip version for deployments

### ISSUE THREAD

**Issue by pamanes** [dataplat/dbops#162]
hi,

According to the docs, the Install-DBOPackage will make sure it installs all builds NOT deployed yet in order, my 1.0 are all CREATE scripts but I have to deploy to a database that has already had the objects created outside of this dbops system.

1) I would like to know if there is a way I can tell the package to always skip 1.0 and deploy anything greater than that that has not been deployed yet (in order).

2) Could I create a new package starting from a specific version to deal with this issue?

thanks,

**Comment by nvarscar** [comment]
1. Indeed! You can use `Register-DBOPackage` with a `-Build` parameter to add the scripts from that build to the schema versions table without deploying them.
2. You can definitely create a new package without the build in question, or you can use `Remove-DBOBuild` to remove the build from the existing package.

**Comment by pamanes** [comment]
Dear lord, this is fantastic! 

thanks a lot for your quick help.
