### ISSUE TITLE
running devops  module  from Azure DevOps

### ISSUE THREAD

**Issue by filippovichv** [dataplat/dbops#163]
i am running  command from my yml file 

pwsh: |

        try { Install-DBOScript -ScriptPath "$(Pipeline.Workspace)\${{ parameters.ArtifactName }}\Migrations\DeploymentScripts" -SqlInstance "${{ parameters.DBServer }}"  -Database "${{ parameters.DBName }}"
             }
        catch {
        Write-Host "An error occurred:"
        Write-Host $_
        }
  
  Script  get executed  fine  ( i see changes in database ) however   I keep getting error right after 
![image](https://github.com/dataplat/dbops/assets/137713487/f0343d78-211d-4dbd-82ff-ed1feba493bb)
 Any suggestions?

**Comment by nvarscar** [comment]
Things I would try:

- Add a Write-Host statement right before/after the Install command inside the try block to see if the command actually throws an exception
- Remove the try/catch block entirely. You can use the -ErrorAction builtin parameter to ignore errors, essentially
- The output looks like the command was successful, I'm not positive the exit code 1 is from running the Install command. Try running it with Verbose/Debug switch to see if there's anything extra to it.

Aside from that there seem to be some suggestions to explicitly specify exit code for Azure tasks in the SO question: https://stackoverflow.com/questions/63508364/azure-devops-reports-powershell-task-as-passed-even-with-non-0-exit-code

**Comment by filippovichv** [comment]
Thank you ... The Install command  is successful and that's why its surprising that i am getting exit code 1. Adding  Exit 0  as suggested in  ticket -works and it seems to catch SQL error or connection error if they exists , guess i ll proceed with this suggestion
